version: "3.8"

services:
  sdn-api:
    container_name: qr-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: npm run dev
